#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['blinker']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='blinker',
      version='1.9.0',
      description='Fast, simple object-to-object and broadcast signaling',
      author='Jason Kirtland',
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      python_requires='>=3.9',
     )
